"use client";

import React from "react";
import { motion } from "framer-motion";
import { Search, ShieldCheck, Activity } from "lucide-react";

export default function TrustLayer() {
  return (
    <section className="relative min-h-screen py-32 px-6 flex flex-col items-center justify-center overflow-hidden">
      
      <div className="absolute inset-0 pointer-events-none bg-gradient-to-t from-[#030014] via-transparent to-[#030014]" />

      <div className="relative z-10 max-w-4xl mx-auto text-center mb-20">
        <motion.h2 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="text-4xl md:text-6xl font-display font-bold text-white mb-6"
        >
          Built for <span className="text-blue-400">Trust</span>
        </motion.h2>
        <motion.p 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="text-xl text-white/50"
        >
          Black-box AI is unacceptable in claims processing. Every decision generated by Nexus Core includes cryptographic audit trails, exact visual citations, and transparent confidence scoring.
        </motion.p>
      </div>

      <div className="relative z-10 w-full max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Metric 1 */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.3 }}
          className="glass p-8 rounded-3xl border border-white/10 flex flex-col items-center text-center group hover:bg-white/[0.03] transition-colors"
        >
          <div className="w-16 h-16 rounded-full bg-blue-500/10 border border-blue-500/20 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <Search className="w-8 h-8 text-blue-400" />
          </div>
          <h3 className="text-5xl font-display font-bold text-white mb-2">100%</h3>
          <p className="text-lg font-medium text-white/80 mb-4">Explainability</p>
          <p className="text-sm text-white/40 leading-relaxed">
            Every rejection or approval is backed by a generated rationale citing specific evidence rules and visual findings.
          </p>
        </motion.div>

        {/* Metric 2 */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.5 }}
          className="glass p-8 rounded-3xl border border-emerald-500/20 bg-emerald-500/5 flex flex-col items-center text-center relative overflow-hidden group hover:bg-emerald-500/10 transition-colors"
        >
          <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-transparent via-emerald-500 to-transparent opacity-50" />
          <div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <ShieldCheck className="w-8 h-8 text-emerald-400" />
          </div>
          <h3 className="text-5xl font-display font-bold text-white mb-2">99.8%</h3>
          <p className="text-lg font-medium text-white/80 mb-4">Precision</p>
          <p className="text-sm text-white/40 leading-relaxed">
            Our multi-agent consensus model effectively eliminates the hallucinations native to single-prompt LLM architectures.
          </p>
        </motion.div>

        {/* Metric 3 */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.7 }}
          className="glass p-8 rounded-3xl border border-white/10 flex flex-col items-center text-center group hover:bg-white/[0.03] transition-colors"
        >
          <div className="w-16 h-16 rounded-full bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <Activity className="w-8 h-8 text-purple-400" />
          </div>
          <h3 className="text-5xl font-display font-bold text-white mb-2">1.8s</h3>
          <p className="text-lg font-medium text-white/80 mb-4">Latency</p>
          <p className="text-sm text-white/40 leading-relaxed">
            Parallelized agent execution allows for real-time validation at the edge, while the user is still uploading evidence.
          </p>
        </motion.div>

      </div>
    </section>
  );
}
